### ISSUE TITLE
Deployment via Helm chart - missing admin password: please set via environment variable, flag or config file

### ISSUE THREAD

**Issue by nodesocket** [freifunkMUC/wg-access-server#82] opened 2022-01-26 21:20 UTC
Using the latest Helm chart version `ghcr.io/freifunkmuc/wg-access-server:v0.5.1` and upon boot, the pod crashes with the following:

```
time="2022-01-26T21:18:27Z" level=fatal msg="missing admin password: please set via environment variable, flag or config file" file="main.go:236"
```

My values file is:

```yaml
wireguard:
  config:
    privateKey: "random-20-alpha-numeric-here"

persistence:
  enabled: true
  size: 1Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  hosts:
    - vpn.acme.dev
  tls:
    - hosts:
        - vpn.acme.dev
```

**Comment by GoliathLabs** [comment] 2022-01-26 21:36
Hi, you need to add an admin password in your values.yaml file ( https://github.com/freifunkMUC/wg-access-server/blob/master/deploy/helm/wg-access-server/values.yaml#L7).

**Comment by GoliathLabs** [comment] 2022-01-26 21:38
If I remember correctly, we don't yet have the option to disable admin access or set a random password if none has been provided.

**Comment by nodesocket** [comment] 2022-01-26 23:31
@GoliathLabs ahh ok. Would be good to update the example values in the readme https://github.com/freifunkMUC/wg-access-server/blob/master/deploy/helm/wg-access-server/README.md

**Comment by nodesocket** [comment] 2022-01-26 23:47
Well, now a new issue. @GoliathLabs and @awlx 

```shell
time="2022-01-26T23:46:35Z" level=info msg="starting wireguard server on :51820" file="main.go:112"
time="2022-01-26T23:46:35Z" level=fatal msg="failed to load wireguard config: failed to set interface ip address: failed to set ip address of wireguard interface: permission denied" file="main.go:123"
```

**Comment by DasSkelett** [comment] 2022-01-27 08:08
If I have to guess, the container is missing CAP_NET_ADMIN. I found this in another repo:
https://github.com/ionos-enterprise/helm-net-cmds/blob/ac9e352c1dfe7a758fdd4558d6d814cd79eac2f5/values.yaml#L5-L8
https://github.com/ionos-enterprise/helm-net-cmds/blob/ac9e352c1dfe7a758fdd4558d6d814cd79eac2f5/templates/daemonset.yaml#L21-L22

But I can't find this documented anywhere on https://helm.sh/docs/ .
@nodesocket, can you confirm whether this is how it's supposed to be done in Helm world, and whether that would make it work?
Also do we need to create a new "DaemonSet" template? If so, is there a documentation somewhere on what needs to be in this template?

**Comment by GoliathLabs** [comment] 2022-01-27 09:43
@DasSkelett, what I find quite interesting is that we have already set the NET_ADMIN security context (https://github.com/freifunkMUC/wg-access-server/blob/master/deploy/helm/wg-access-server/templates/deployment.yaml#L34)

**Comment by nodesocket** [comment] 2022-01-27 23:27
@GoliathLabs I took a quick peek and confirm the addition of `NET_ADMIN` looks right at:

https://github.com/freifunkMUC/wg-access-server/blob/master/deploy/helm/wg-access-server/templates/deployment.yaml#L34

Do we need `allowPrivilegeEscalation: true`?

Doing a describe on the pod does not show `NET_ADMIN` is set, but perhaps that is just not added to describe?

```
kubectl describe pod wg-access-server-85bcfcdb96-x576r | grep "NET_ADMIN"
```

**Comment by zandemax** [comment] 2022-02-01 17:11
Hi @nodesocket, I can replicate your problem on my machine. It has nothing to do with privileges as far as I can tell, but rather it is caused by IPv6.
As a quick fix you can try to disable IPv6 by adding the following snippet to your values.yaml:
```yaml
config:
  vpn:
    cidrv6: 0
```
This fixes the problem for me, and the server starts normally.
Unfortunately, i was not yet able to find the root cause for this, since it works fine running in a plain docker container with IPv6 enabled.

**Comment by DasSkelett** [comment] 2022-02-01 17:25
Ah! Thanks for the notes @zandemax!
New guess based on that: `net.ipv6.conf.all.disable_ipv6` is `1` by default in k8s containers?
It is at least in normal Docker and you have to pass `--sysctl net.ipv6.conf.all.disable_ipv6=0` and `--sysctl net.ipv6.conf.all.forwarding=1` to the `docker run` command.

Next question then: how to set sysctls in the templates and does it really fix it? @zandemax is there a chance you could try this out?

**Comment by zandemax** [comment] 2022-02-01 17:38
Hi @DasSkelett, good guess! `net.ipv6.conf.all.disable_ipv6` is indeed `1` in the container.
I also read up on it a little, and it appears that IPv6 is not really a first-class citizen in the k8s-world (yet). IPv6 support is generally available since 1.20 and enabled by default since 1.21, but only if your network plugin supports it (as far as i found out thats only true for Calico and Kubenet so far). 
Some more info on that here: https://kubernetes.io/docs/concepts/services-networking/dual-stack/. 
Minikube for example does not support IPv6 at all to date.

I will try to verify that this is true and that it works as expected with IPv6 on a cluster that should have IPv6 support enabled.
Nonetheless, I would probably advise to add a note to the documentation detailing the problem with Kubernetes and IPv6 support.

**Comment by DasSkelett** [comment] 2022-02-01 21:17
Yeah, Kubernetes, like most of the container world unfortunately, are still a bit behind with IPv6.

Ideally we would get it to work correctly with IPv6 enabled on k8s. I have to think about a "IPv6-detection" feature for a little; this automagic behind-the-scenes type of features always increases complexity (need to interface with sysctl, what to do when the user explicitly enabled it but our detection says no), tends to hide actual problems (broken container/config/setup) while possibly causing confusion among users (no IPv6 even though they expected it because everywhere else it's enabled by default).

I prefer to stick to the options that already exist for this: the config file (or command arguments or env vars), where you can disable features if your particular setup doesn't support it.

However I think I found the way to set the sysctls in k8s containers. It's possible that there's more work required though.
If I traced the docs backwards correctly, we would need to add the following to the Helm template:
```yaml
spec:
  template:
    spec:
      containers:
        - ...
      securityContext:
        sysctls:
          - name: net.ipv6.conf.all.disable_ipv6
            value: 0
          - name: net.ipv6.conf.all.forwarding
            value: 1
```
<details>
<summary>Documentation links:</summary>

- [Deployment](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#deployment-v1-apps)
- [DeploymentSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#deploymentspec-v1-apps)
- [PodTemplateSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#podtemplatespec-v1-core)
- [PodSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#podspec-v1-core)
- [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#podsecuritycontext-v1-core)
- [Sysctl](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#sysctl-v1-core)

sysctls seem to be set pod-wide, because `deployment.spec.template.spec.containers.x.securityContext` doesn't have a `sysctls` field, so it's not set within the existing `securityContext` field we have in the container array:
- [Container](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#container-v1-core)
- [SecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#securitycontext-v1-core)
</details>

But if this is still broken on Kubernetes, we could think about setting `config.vpn.cidrv6` to `0` in `values.yaml` as you already suggested, that would make the application work by default in Kubernetes when using our Helm templates, should be easy to override for users who have a proper IPv6 setup, and doesn't affect anything outside k8s.

**Comment by zandemax** [comment] 2022-02-02 13:21
@DasSkelett I tried out your idea of setting the sysctls on the pod. 
Unfortunately, that does not work, as there is only a certain list of 'allowed' sysctls that you can set on a pod, and `net.ipv6.conf.all.disable_ipv6` is not among them, and would have to be enabled by setting a flag on the kubelet.
Documentation on this: https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/
So as far as I can see it, there is really no good way of using IPv6 in a pod without having an IPv6 / dual-stack k8s cluster.

I tested the current helm template on a dual-stack cluster though and it worked as expected there. I was not able to test it on an IPv6-only cluster yet, since I don't have one running/available right now.
Since it can probably be assumed that the majority of all k8s-clusters out there is still IPv4-only though, I think it would be a good idea to disable IPv6 by default in `values.yaml`, and let users explicitly enable it if they have a cluster that supports it.

**Comment by nodesocket** [comment] 2022-02-02 15:03
@zandemax agree the way to go is disable ipv6 by default in values.yaml.

**Comment by GoliathLabs** [comment] 2022-02-04 15:36
@nodesocket is it working now? We have merged the PR of @zandemax.

**Comment by nodesocket** [comment] 2022-02-04 23:48
@GoliathLabs thanks for all the help. I honestly switched to using the project [wg-easy](https://github.com/WeeJeWel/wg-easy) as the fancy bandwidth graphs candy caught my attention. _squirrel_

**Closed** 2022-02-05 08:43 UTC
Labels: bug, help wanted, question
